#define DEFAULT_WIDTH 50
#define DEFAULT_HEIGHT 50
#define MAX_TOTAL_ENTITIES 500

// Kezdő entitás számok
#define INITIAL_PLANTS 120
#define INITIAL_HERBIVORES 20
#define INITIAL_CARNIVORES 3

// Max entity szám
#define MAX_PLANTS 250
#define MAX_HERBIVORES 200
#define MAX_CARNIVORES 25

#define PLANT_MAX_ENERGY 20
#define PLANT_INITIAL_ENERGY 10
#define PLANT_REPRODUCTION_PROBABILITY 0.54 // Szaporodási esély lépésenként, ha a feltételek adottak
#define PLANT_REPRODUCTION_COOLDOWN 1       // Minimum lépésszám két szaporodás között
#define PLANT_MAX_AGE 40
#define PLANT_GROWTH_RATE 1
#define EATEN_ENERGY_MARKER -1

#define HERBIVORE_INITIAL_ENERGY 100
#define HERBIVORE_MAX_ENERGY 300
#define HERBIVORE_ENERGY_DECAY 2 // Alap energiafogyasztás lépésenként
#define HERBIVORE_MOVE_COST 1
#define HERBIVORE_SIGHT_RANGE 7
#define HERBIVORE_MAX_AGE 80
#define HERBIVORE_REPRODUCTION_THRESHOLD 150 // Minimális energia a szaporodáshoz
#define HERBIVORE_REPRODUCTION_COST 90
#define HERBIVORE_REPRODUCTION_COOLDOWN 5 // Minimum lépésszám két szaporodás között
#define HERBIVORE_ENERGY_FROM_PLANT 50
#define HERBIVORE_CRITICAL_ENERGY_THRESHOLD 20 // Ha ez alá esik, csak enni próbál

#define CARNIVORE_INITIAL_ENERGY 150
#define CARNIVORE_MAX_ENERGY 200
#define CARNIVORE_ENERGY_DECAY 2
#define CARNIVORE_MOVE_COST 4
#define CARNIVORE_SIGHT_RANGE 6
#define CARNIVORE_MAX_AGE 80
#define CARNIVORE_REPRODUCTION_THRESHOLD 150
#define CARNIVORE_REPRODUCTION_COST 75
#define CARNIVORE_REPRODUCTION_COOLDOWN 10
#define CARNIVORE_ENERGY_FROM_HERBIVORE 70
#define CARNIVORE_CRITICAL_ENERGY_THRESHOLD 50 // Ha ez alá esik, csak enni próbál